import {expansionGames} from './expansion-catalog.js?v=20261007';
export const games = [
 {id:'pinball',title:'Neon Pinball',sport:'Pinball',group:'Arcade',color:'#c1a1f4',controls:'Tap either side to flip. Tap LAUNCH to serve. Two thumbs or one finger.',hint:'Tap left / right flipper · Keyboard: ← → and Space',pitch:'Light up the bumpers. Keep the ball alive.',duration:'3 balls',action:['LEFT FLIP','RIGHT FLIP']},
 {id:'soccer',title:'Top Corner',sport:'Association football',group:'Ball sports',color:'#a9d4a2',controls:'Drag across the goal to aim. Release to shoot past the moving keeper. Ten shots.',hint:'Drag to aim, release to shoot · Keyboard: ← →, Space',pitch:'One shot. One keeper. Find the top corner.',duration:'10 shots',action:['SHOOT']},
 {id:'football',title:'End Zone Rush',sport:'American football',group:'Ball sports',color:'#e8b78e',controls:'Slide your thumb to dodge defenders. Cross the field for a touchdown. Three tackles end the run.',hint:'Drag left / right to dodge · Keyboard: ← →',pitch:'Find the gap. Take it all the way.',duration:'60 seconds',action:[]},
 {id:'tennis',title:'Baseline Club',sport:'Tennis',group:'Ball sports',color:'#dbdf9c',controls:'Slide to move your racket. Returns are automatic. Aim with the edge of your racket to beat your opponent. First to seven wins.',hint:'Drag to move · Keyboard: ← →',pitch:'Own the baseline, one rally at a time.',duration:'First to 7',action:[]},
 {id:'rugby',title:'Try Line',sport:'Rugby',group:'Ball sports',color:'#88c9c5',controls:'Slide to dodge tacklers. Tap PASS to switch to your support runner. Score five-point tries. Three tackles end the run.',hint:'Drag to run · Tap PASS · Keyboard: ← →, Space',pitch:'Dodge the tackle. Time the pass. Score the try.',duration:'60 seconds',action:['PASS']},
 {id:'moto',title:'Midnight Moto',sport:'Moto racing',group:'Racing',color:'#b4b4ea',controls:'Slide to steer through traffic. Collect gold rings and ride 3 km. Three crashes end the ride.',hint:'Drag to steer · Keyboard: ← →',pitch:'Chase the lights. Thread the traffic.',duration:'3 km sprint',action:[]},
 {id:'formula',title:'Apex Circuit',sport:'Open-wheel racing',group:'Racing',color:'#ee9c82',controls:'Slide to steer with the bends. Hold BRAKE through corners. Finish three laps before taking three hits.',hint:'Drag to steer · Hold BRAKE · Keyboard: ← →, Space',pitch:'Chase the apex. Make every lap count.',duration:'3 laps',action:['BRAKE']},
 {id:'snake',title:'Snake Garden',sport:'Classic Snake',group:'Arcade',color:'#bcda9d',controls:'Swipe or tap the direction buttons to steer. Eat the fruit to grow. Avoid the walls and your tail. The pace picks up with every snack.',hint:'Swipe or tap arrows · Keyboard: arrows / WASD',pitch:'A familiar little snake. An ever-growing challenge.',duration:'High-score run',action:[]},
 {id:'chess',title:'Quiet Chess',sport:'Chess',group:'Board games',color:'#b7cbb7',controls:'You play White against a casual computer opponent, or choose Pass & play for two people. Tap a piece, then a highlighted square. Castling, en passant and promotion are supported.',hint:'Tap piece, then square · Keyboard: arrows + Enter',pitch:'Slow down. Think ahead. Make your next move.',duration:'Solo or 2 players',action:[]},
 {id:'checkers',title:'Crown Checkers',sport:'Checkers',group:'Board games',color:'#dcb99e',controls:'Ivory moves first. Tap a piece and its destination. Captures are mandatory; complete every jump. Men move and capture forward; kings move both ways. Crowning ends your turn. Three repeated positions or 80 quiet turns draw.',hint:'Tap piece, then square · Keyboard: arrows + Enter',pitch:'Find the jump. Reach the crown. Rule the board.',duration:'Solo or 2 players',action:[]},
 {id:'reversi',title:'Flipside',sport:'Reversi',group:'Board games',color:'#98c8bd',controls:'You play Dark. Tap a highlighted square to trap and flip the other colour. Dark moves first. Turns pass automatically if no move is available. Most discs at the end wins.',hint:'Tap a highlighted square · Keyboard: arrows + Enter',pitch:'Turn the tables with a single disc.',duration:'Solo or 2 players',action:[]},
 ...expansionGames
];
